name: Pipeline

on:
    push:
        branches: ["main"]

    workflow_dispatch:

env:
    AWS_DEFAULT_REGION: us-east-1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS CLI
              run: |
                  sudo apt install -y awscli
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set default_region_name ${{ secrets.AWS_DEFAULT_REGION_NAME }}
                  aws configure set default_output_format JSON

            - name: Init Terraform
              run: cd terraform && terraform init

            - name: Apply Terraform
              run: cd terraform && terraform apply -auto-approve

    deploy:
        runs-on: ubuntu-latest
        # needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS CLI
              run: |
                  sudo apt install -y awscli
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set default_region_name ${{ secrets.AWS_DEFAULT_REGION_NAME }}
                  aws configure set default_output_format JSON

            - name: Run SQL script
              run: |
                  mysql -u ${{ secrets.RDS_DATABASE_USER }} -p${{ secrets.RDS_DATABASE_PASSWORD }} -P 3306 -h dbhacka.cd6yk7z7kstc.${{ env.AWS_DEFAULT_REGION }}.rds.amazonaws.com < scripts/init.sql 
